exports.courses = [
    "electrical engineering",
    "law",
    "mathematics",
    'computer science',
    'biochemistry',
    'chemical engineering',
    'physics and solar energy',
    'medaical lab science',
    'sociology',
    'chemistry',
    'accounting',
    'business administration',
    'economics',
    'data analysis',
    'linguistics',
    'agricultural engineering',
    'project management',
    'civil engineering',
    'mechanical engineering',
    'Nursing',
    'geology',
    'geography',
    'theatre arts',
    'Languages',
    'architecture',
    'civic education',
    'history',
    'philosophy',
    'transport management'

]

