const { QueryInterface } = require("sequelize");
const { uuid } = require('uuidv4');
const allcountries = require('./countries')
const randomPick = Math.floor(Math.random() * Number(allcountries.length))
const randomCountry = allcountries[randomPick]

module.exports = {
    up: async(QueryInterface, sequelize) => {
        await QueryInterface.bulkInsert(
            "Universities",
            [
                {   id: uuid(),
                    name:"university of avengers",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]

                },
                 {   id: uuid(),
                    name:"university of gotham",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                 {   id: uuid(),
                    name:"university of marvel",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]

                },
                 {   id: uuid(),
                    name:"university of multiverse",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]

                },
                 {   id: uuid(),
                    name:"university of metropolis",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                 {   id: uuid(),
                    name:"university of newyork",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of washington",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of califonia",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of Lagos",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of ibadan",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of columbia",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                 {   id: uuid(),
                    name:"university of accra",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of paris",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of abuja",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of munich",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of ogun",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of london",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of newyork",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of whales",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },
                {   id: uuid(),
                    name:"university of leicester",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },                               
                {   id: uuid(),
                    name:"university of brandford",
                    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac felis donec et odio pellentesque diam volutpat commodo sed.",
                    ratings: 3,
                    address: 'Lorem ipsum dolor sit amet',
                    created_at: new Date(),
                    updated_at: new Date(),
                    country: allcountries[Math.floor(Math.random() * Number(allcountries.length))]
                },

            ]
        )
    }
}